services:
  kbtc_app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env.kbtc
    networks:
      - kbtc_network
    ports:
      - "${PORT:-14010}:3000"

  ibtc_app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env.ibtc
    networks:
      - ibtc_network
    ports:
      - "${PORT:-14011}:3000"

networks:
  kbtc_network:
  ibtc_network:
